# Site settings
title: Î»phonic
email: info@lambdaphonic.de
description: Code is Music
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lambdaphonic.de" # the base hostname & protocol for your site
twitter_username: lambdaphonic
github_username:  lambdaphonic
soundcloud_username: lambdaphonic

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - .vscode
  - .sass-cache
  - .vendor
  - run_server.sh
lsi: false
permalink: /posts/:title/
author:
  name: lambdaphonic
  email: info@lambdaphonic.de
defaults:
  - scope:
      path: ""
    values:
      excerpt_separator: <!-- more -->
      layout: post
      author: lambdaphonic
