# Site settings
title: Î» phonic
email: info@lambdaphonic.de
description: Music by code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lambdaphonic.de" # the base hostname & protocol for your site
twitter_username: magicmonty
github_username:  lambdaphonic

# Build settings
markdown: kramdown
